version: '3'

tasks:

  generate:
    description: "generate mocks"
    cmds:
      - go install go.uber.org/mock/mockgen@v0.4.0
      - go generate ./...

  test-all:
    description: "run unit and integration tests"
    cmds:
      - go test -tags=integration -coverprofile coverage.out -race ./...
  
  test-short:
    description: "run unit tests only"
    cmds:
      - go test -coverprofile coverage.out -race ./...
