name: Qualification

on:
  push:
    branches-ignore:
      - main

jobs:
  qualification:
    name: Qualification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
      
      - name: Install Task
        uses: arduino/setup-task@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unit and Integration tests
        run: |
          task test-all

      - name: Code Coverage Job Summary
        uses: notmiguelalves/go-coverage-summary@v0.4.0
        with:
          coverage-file: "coverage.out"
