name: Qualification

on:
  push:

jobs:
  qualification:
    name: Qualification
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
      
      - name: Install Task
        uses: arduino/setup-task@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup docker
        if: runner.os == 'macos'
        run: |
          brew install docker
          colima start
          ln -s ~/.docker/run/docker.sock /var/run/docker.sock

      - name: Unit and Integration tests
        run: |
          task test-all
